# Generated by Django 2.1.5 on 2019-02-27 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role name')),
                ('desc', models.TextField(verbose_name='Role Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Company email Address'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Upload Organisation Logo'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organisation', to='users.Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Organisation Address Location'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of Organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
