# Generated by Django 2.1.5 on 2019-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190302_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Upload Organisation Logo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_num',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name="User's phone number"),
        ),
    ]
